# Generated by Django 3.1.3 on 2022-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
